# Generated by Django 4.2.7 on 2024-11-10 03:58

from django.db import migrations, models
import voter_analytics.models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='id',
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_id_num',
            field=models.CharField(default=voter_analytics.models.Voter.generate_voter_id, max_length=100, primary_key=True, serialize=False),
        ),
    ]
