# Generated by Django 4.2.7 on 2024-11-10 05:16

from django.db import migrations, models
import voter_analytics.models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_remove_voter_id_voter_voter_id_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_id_num',
            field=models.CharField(default=voter_analytics.models.Voter.generate_voter_id, max_length=100),
        ),
    ]
