# Generated by Django 4.2.7 on 2024-11-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='total_num',
        ),
        migrations.AddField(
            model_name='flight',
            name='total_num',
            field=models.IntegerField(default=100),
        ),
    ]
