# Generated by Django 4.2.7 on 2024-11-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_remove_ticket_total_num_flight_total_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
