# Generated by Django 4.2.7 on 2024-12-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_cartitem_total_price_ticket_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
