# Generated by Django 4.2.7 on 2024-12-09 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_ticket_checked_in_ticket_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboard', models.CharField(choices=[('first_cabin', 'First Cabin'), ('second_cabin', 'Second Cabin')], default='second_cabin', max_length=20)),
                ('passenger_count', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('is_member', models.BooleanField(default=False)),
                ('has_delta_card', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baggages', to='flights.ticket')),
            ],
        ),
    ]
