# Generated by Django 4.2.7 on 2024-12-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_alter_ticket_seat_number_baggage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baggage',
            name='passenger_count',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
