# Generated by Django 4.2.7 on 2024-12-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_alter_baggage_passenger_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='baggage',
            name='is_checkout',
            field=models.BooleanField(default=False),
        ),
    ]
